### ISSUE TITLE
A little bit buggy

### ISSUE THREAD

**Issue by SheepCommander** [SammCheese/At-Someone#3]
![image](https://user-images.githubusercontent.com/66646514/148684282-27289bae-4db3-464d-b2f8-54ad1f7d83a8.png)

![image](https://user-images.githubusercontent.com/66646514/148684283-94be8790-9af8-4504-8d57-636b68763597.png)

Doesn't replace the existing @some text

**Comment by SammCheese** [comment]
Couldnt fix this one entirely, the @some@!someone is purely visual now and gets replaced with @!someone on send

**Comment by SammCheese** [comment]
![image](https://user-images.githubusercontent.com/52699291/148724658-da4b6e3e-3672-4ad7-9f63-45f57a60b439.png)
![image](https://user-images.githubusercontent.com/52699291/148724666-e6dfe551-459d-4bb5-a477-bab8ca45e7a1.png)

**Comment by SheepCommander** [comment]
Alright thanks
